# Generated by Django 6.1.1 on 2026-09-09 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('clave_union', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_creada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_escritas', to=settings.AUTH_USER_MODEL)),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='parejas.pareja')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='parejas.pareja')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='parejas_archivos/')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('favorito', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='parejas.pareja')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='parejas.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas', to=settings.AUTH_USER_MODEL)),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='parejas.pareja')),
            ],
            options={
                'unique_together': {('pareja', 'usuario')},
            },
        ),
    ]
